[tool.poetry]
name = "nlpquery"
version = "0.1.0"
description = ""
authors = ["Ryan Stout <ryanstout@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
sqlglot = "^10.4.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
