[tool.poetry]
name = "nlpquery"
version = "0.1.0"
description = ""
authors = ["Ryan Stout <ryanstout@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
sqlglot = "^10.4.3"
snowflake-connector-python = "^2.9.0"
prisma-client = "^0.2.1"
prisma = "^0.8.0"
python-decouple = "^3.7"
openai = {extras = ["embeddings"], version = "^0.26.1"}
python-dotenv = "^0.21.0"
ipython = "^8.8.0"
faiss-cpu = "^1.7.3"
xxhash = "^3.2.0"
tiktoken = "^0.1.2"
sentence-transformers = "^2.2.2"
structlog = "^22.3.0"
click = "^8.1.3"


[tool.poetry.group.dev.dependencies]
autopep8 = "^2.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
